ForeverLevelingCoach_Data = {
    version = "0.17.5",
    supported = {
        faction = "Horde",
        classes = {
            SHAMAN = true,
            ROGUE = true,
        },
        minLevel = 1,
        maxLevel = 30,
    },

    knownQuestIDs = {
        [364] = true, -- The Mindless Ones (Undead starter, live-verified on Ms)
        [380] = true, -- Night Web's Hollow
        [6395] = true, -- Marla's Last Wish
        [98389] = true, -- A Light in the Darkness
        [408] = true, -- The Family Crypt (verified in Forever DB)
        [372] = true, -- At War With The Scarlet Crusade (verified in Forever DB)
        [371] = true, -- At War With The Scarlet Crusade (verified in Forever DB)
        [492] = true, -- A New Plague (verified in Forever DB)
        [369] = true, -- A New Plague (verified in Forever DB)
        [368] = true, -- A New Plague (verified in Forever DB)
        [367] = true, -- A New Plague (verified in Forever DB)
        [8] = true, -- A Rogue's Deal delivery (verified in Forever DB)
        [590] = true, -- A Rogue's Deal (verified in Forever DB)
        [381] = true, -- The Scarlet Crusade (verified in Forever DB)
        [382] = true, -- The Red Messenger (live-verified on Ms; Forever DB cross-check)
        [383] = true, -- Vital Intelligence (Forever DB chain follow-up)
        [407] = true, -- Fields of Grief (Classic chain follow-up verified in Forever DB)
        [365] = true, -- Fields of Grief (Classic quest verified present on Ms)
        [86784] = true, -- Sticks and Bones (Forever-exclusive Brill side quest)
        [96607] = true, -- The Great Outdoors (Forever-exclusive Undead camping tutorial follow-up)
        [96656] = true, -- The Adventurer (Forever-exclusive Undead camping intro; live-verified on Ms)
        [3902] = true, -- Scavenging Deathknell (verified in Forever DB)
        [3096] = true, -- Encrypted Scroll (live-verified on Ms)
        [3901] = true, -- Rattling the Rattlecages (live-verified on Ms)
        [376] = true, -- The Damned (live-verified on Ms)
        [1527] = true,  -- Call of Fire: Horde Shaman Fire Totem / Totem of Charged Flames
        [2986] = true,
        [1534] = true,
        [1536] = true,
        [220] = true,  -- Call of Water: Vial of Purest Water to Islen Waterseer
        [63] = true,   -- Call of Water: Corrupt Manifestation's Bracers / Silverpine cleanse
        [96] = true,   -- Call of Water: return Shard of Water to Islen Waterseer
        [100] = true,  -- Call of Water: speak with Minor Manifestation of Water
        [1103] = true, -- Call of Water recovery: bring Water Sapta to Tiev Mordune
        [6503] = true, -- Ashenvale Outrunners
        [6441] = true, -- Satyr Horns
        [6548] = true, -- Avenge My Village
        [1062] = true, -- Goblin Invaders
        [6543] = true, -- The Warsong Reports
        [6571] = true, -- Warsong Supplies (live-discovered in Forever)
        [6921] = true, -- Amongst the Ruins (live-discovered in Forever)
        [6563] = true, -- The Essence of Aku'Mai (live-discovered in Forever)
        [6462] = true, -- Troll Charm (live-discovered in Forever)
        [216] = true, -- Between a Rock and a Thistlefur (live-discovered in Forever)
        [6641] = true, -- Vorsha the Lasher (live-discovered in Forever)
        [6442] = true, -- Naga at the Zoram Strand (live-discovered in Forever)
        [1489] = true, -- Hamuul Runetotem
        [1483] = true, -- Ziz Fizziks (live-discovered in Forever)
        [6981] = true, -- The Glowing Shard
        [3369] = true, -- In Nightmares (live-discovered in Forever)
        [1098] = true, -- Deathstalkers in Shadowfang (live-discovered in Forever)
        [1013] = true, -- The Book of Ur (live-discovered in Forever)
        [1014] = true, -- Arugal Must Die (live-discovered in Forever)
        [914] = true,  -- Leaders of the Fang (live-discovered in Forever)
        [1490] = true, -- Nara Wildmane (live-discovered in Forever)
    },

    shamanWeaponPreference = {
        mode = "2H_ONLY",
        allowedSubTypes = {
            ["Two-Handed Axes"] = true,
            ["Two-Handed Maces"] = true,
        },
        label = "2H Axe / 2H Mace",
    },

    rogueTalentBuilds = {
        defaultSpec = "Combat",
        Combat = {
            name = "Combat",
            purpose = "Best all-around leveling / dungeon quest build",
            source = "Mobalytics WoW Forever Combat / Rogue Leveling guides",
            final30 = "0/21/0",
            talentsByLevel = {
                [10] = { talent = "Improved Sinister Strike", rank = 1, maxRank = 2 },
                [11] = { talent = "Improved Sinister Strike", rank = 2, maxRank = 2 },
                [12] = { talent = "Improved Eviscerate", rank = 1, maxRank = 3 },
                [13] = { talent = "Improved Eviscerate", rank = 2, maxRank = 3 },
                [14] = { talent = "Improved Eviscerate", rank = 3, maxRank = 3 },
                [15] = { talent = "Precision", rank = 1, maxRank = 3 },
                [16] = { talent = "Precision", rank = 2, maxRank = 3 },
                [17] = { talent = "Precision", rank = 3, maxRank = 3 },
                [18] = { talent = "Deflection", rank = 1, maxRank = 3 },
                [19] = { talent = "Deflection", rank = 2, maxRank = 3 },
                [20] = { talent = "Deflection", rank = 3, maxRank = 3 },
                [21] = { talent = "Riposte", rank = 1, maxRank = 1 },
                [22] = { talent = "Endurance", rank = 1, maxRank = 2 },
                [23] = { talent = "Endurance", rank = 2, maxRank = 2 },
                [24] = { talent = "Improved Sprint", rank = 1, maxRank = 2 },
                [25] = { talent = "Dual Wield Specialization", rank = 1, maxRank = 5 },
                [26] = { talent = "Dual Wield Specialization", rank = 2, maxRank = 5 },
                [27] = { talent = "Dual Wield Specialization", rank = 3, maxRank = 5 },
                [28] = { talent = "Dual Wield Specialization", rank = 4, maxRank = 5 },
                [29] = { talent = "Dual Wield Specialization", rank = 5, maxRank = 5 },
                [30] = { talent = "Blade Flurry", rank = 1, maxRank = 1 },
            },
        },
        Assassination = {
            name = "Assassination",
            purpose = "Popular single-target / Mutilate build",
            source = "Mobalytics WoW Forever Assassination guide",
            final30 = "21/0/0",
            talentsByLevel = {
                [10] = { talent = "Malice", rank = 1, maxRank = 5 },
                [11] = { talent = "Malice", rank = 2, maxRank = 5 },
                [12] = { talent = "Malice", rank = 3, maxRank = 5 },
                [13] = { talent = "Malice", rank = 4, maxRank = 5 },
                [14] = { talent = "Malice", rank = 5, maxRank = 5 },
                [15] = { talent = "Ruthlessness", rank = 1, maxRank = 3 },
                [16] = { talent = "Ruthlessness", rank = 2, maxRank = 3 },
                [17] = { talent = "Ruthlessness", rank = 3, maxRank = 3 },
                [18] = { talent = "Improved Slice and Dice", rank = 1, maxRank = 3 },
                [19] = { talent = "Improved Slice and Dice", rank = 2, maxRank = 3 },
                [20] = { talent = "Lethality", rank = 1, maxRank = 5 },
                [21] = { talent = "Lethality", rank = 2, maxRank = 5 },
                [22] = { talent = "Lethality", rank = 3, maxRank = 5 },
                [23] = { talent = "Lethality", rank = 4, maxRank = 5 },
                [24] = { talent = "Lethality", rank = 5, maxRank = 5 },
                [25] = { talent = "Relentless Strikes", rank = 1, maxRank = 1 },
                [26] = { talent = "Cold Blood", rank = 1, maxRank = 1 },
                [27] = { talent = "Remorseless Attacks", rank = 1, maxRank = 2 },
                [28] = { talent = "Remorseless Attacks", rank = 2, maxRank = 2 },
                [29] = { talent = "Improved Slice and Dice", rank = 3, maxRank = 3 },
                [30] = { talent = "Mutilate", rank = 1, maxRank = 1 },
            },
        },
        Subtlety = {
            name = "Subtlety",
            purpose = "Popular PvP / Hemorrhage build",
            source = "Mobalytics WoW Forever Subtlety guide",
            final30 = "0/0/21",
            talentsByLevel = {
                [10] = { talent = "Opportunity", rank = 1, maxRank = 2 },
                [11] = { talent = "Opportunity", rank = 2, maxRank = 2 },
                [12] = { talent = "Camouflage", rank = 1, maxRank = 5 },
                [13] = { talent = "Camouflage", rank = 2, maxRank = 5 },
                [14] = { talent = "Camouflage", rank = 3, maxRank = 5 },
                [15] = { talent = "Improved Ambush", rank = 1, maxRank = 3 },
                [16] = { talent = "Improved Ambush", rank = 2, maxRank = 3 },
                [17] = { talent = "Improved Ambush", rank = 3, maxRank = 3 },
                [18] = { talent = "Setup", rank = 1, maxRank = 3 },
                [19] = { talent = "Setup", rank = 2, maxRank = 3 },
                [20] = { talent = "Ghostly Strike", rank = 1, maxRank = 1 },
                [21] = { talent = "Initiative", rank = 1, maxRank = 3 },
                [22] = { talent = "Initiative", rank = 2, maxRank = 3 },
                [23] = { talent = "Initiative", rank = 3, maxRank = 3 },
                [24] = { talent = "Setup", rank = 3, maxRank = 3 },
                [25] = { talent = "Serrated Blades", rank = 1, maxRank = 3 },
                [26] = { talent = "Serrated Blades", rank = 2, maxRank = 3 },
                [27] = { talent = "Serrated Blades", rank = 3, maxRank = 3 },
                [28] = { talent = "Premeditation", rank = 1, maxRank = 1 },
                [29] = { talent = "Camouflage", rank = 4, maxRank = 5 },
                [30] = { talent = "Hemorrhage", rank = 1, maxRank = 1 },
            },
        },
    },

    rogueGearProfile = {
        armorPreferred = "Leather",
        armorAllowed = {
            ["Cloth"] = true,
            ["Leather"] = true,
        },
        meleeWeapons = {
            ["Daggers"] = true,
            ["One-Handed Swords"] = true,
            ["One-Handed Maces"] = true,
            ["Fist Weapons"] = true,
        },
        rangedWeapons = {
            ["Thrown"] = true,
            ["Bows"] = true,
            ["Crossbows"] = true,
            ["Guns"] = true,
        },
        levelingStats = {
            agility = 2.2,
            stamina = 0.8,
            strength = 0.5,
            intellect = 0.0,
            spirit = 0.0,
        },
    },

    shamanRelics = {
        [263412] = {
            name = "Totem of Charged Flames",
            slot = 18,
            score = 25,
            effect = "Reduces the mana cost of Flame Shock and Lightning Bolt by 5 Mana.",
            sourceQuestIDs = { 1527 },
            note = "Forever-specific Shaman relic. Equip it in the Totem/Relic slot.",
        },
    },

    shamanTrainers = {
        names = {
            ["Kardris Dreamseeker"] = true,
            ["Sagorne Creststrider"] = true,
            ["Sian'tsu"] = true,
            ["Beram Skychaser"] = true,
            ["Siln Skychaser"] = true,
            ["Tigor Skychaser"] = true,
            ["Swart"] = true,
            ["Narm Skychaser"] = true,
            ["Shikrik"] = true,
            ["Meela Dawnstrider"] = true,
        },
        orgrimmar = {
            city = "Orgrimmar",
            name = "Kardris / Sagorne / Sian'tsu",
            zone = "Valley of Wisdom, Orgrimmar",
            coords = "38.9, 36.4",
            mapID = 1454,
            x = 0.389,
            y = 0.364,
        },
        thunderBluff = {
            city = "Thunder Bluff",
            name = "Beram / Siln / Tigor Skychaser",
            zone = "Spirit Rise, Thunder Bluff",
            coords = "22.0, 18.8",
            mapID = 1456,
            x = 0.220,
            y = 0.188,
        },
    },

    -- Adaptive smart-route scoring. Higher score = better next step.
    -- These are intentionally simple and explainable so exports can show why
    -- the addon made a recommendation.
    scoring = {
        tag = {
            IMPORTANT = 1000,
            DO = 300,
            OPTIONAL = 120,
            SKIP = -500,
        },
        completedTurnIn = 180,
        currentZoneCluster = 170,
        rememberedCluster = 60,
        clusterQuest = 22,
        partialProgressMax = 80,
        waypointNearMax = 90,
        clusterPriorityMax = 30,
    },

    -- Quest clusters let the router keep you in one area and stack nearby
    -- objectives instead of bouncing between zones after every quest.
    clusters = {
        TIRISFAL_BRILL = {
            name = "Tirisfal / Brill",
            zoneAliases = { "Tirisfal Glades", "Brill" },
            note = "Fast Undead hub after Deathknell. Stack Brill, Scarlet, plague, and Agamand work.",
        },
        SILVERPINE_ROGUE = {
            name = "Silverpine Forest",
            zoneAliases = { "Silverpine Forest", "The Sepulcher" },
            note = "Primary Undead follow-up zone after Tirisfal for fast 10-18 leveling.",
        },
        TIRISFAL_DEATHKNELL = {
            name = "Tirisfal / Deathknell",
            zoneAliases = { "Tirisfal Glades", "Deathknell", "Shadow Grave" },
            note = "Undead starter cluster. Keep early Deathknell quests stacked together.",
        },
        ASHENVALE_ZORAM = {
            name = "Ashenvale / Zoram Strand",
            zoneAliases = { "Ashenvale", "Zoram'gar Outpost", "Zoram Strand" },
            note = "Bundle Zoram Strand naga/event quests while you are already on the west coast.",
        },
        ASHENVALE_THISTLEFUR = {
            name = "Ashenvale / Thistlefur",
            zoneAliases = { "Ashenvale", "Thistlefur Village", "Thistlefur Hold" },
            note = "Bundle Thistlefur kills, Troll Charms, and Logging Rope when moving through central-west Ashenvale.",
        },
        ASHENVALE_SPLINTERTREE = {
            name = "Ashenvale / Splintertree",
            zoneAliases = { "Ashenvale", "Splintertree Post" },
            note = "Stack the nearby Ashenvale objectives before leaving the area.",
        },
        STONETALON_GRIMTOTEM = {
            name = "Stonetalon / Grimtotem",
            zoneAliases = { "Stonetalon Mountains", "Stonetalon", "Camp Aparaje" },
            note = "Finish the nearby Grimtotem and Venture Co. objectives together when you are already in Stonetalon.",
        },
        SILVERPINE_WATER = {
            name = "Silverpine / Water Totem",
            zoneAliases = { "Silverpine Forest", "Silverpine" },
            note = "Stay on the Water Totem objective while you are in Silverpine.",
        },
        BARRENS_RATCHET = {
            name = "Barrens / Ratchet",
            zoneAliases = { "The Barrens", "Barrens", "Ratchet" },
            note = "Handle Ratchet/Barrens hand-ins while passing through instead of making a special trip.",
        },
        THUNDER_BLUFF = {
            name = "Thunder Bluff",
            zoneAliases = { "Thunder Bluff" },
            note = "Bundle Thunder Bluff hand-ins with trainer, bank, auction, or travel stops.",
        },
        SHADOWFANG_KEEP = {
            name = "Shadowfang Keep",
            dungeon = true,
            zoneAliases = { "Shadowfang Keep" },
            note = "Dungeon cluster: while inside SFK, finish active SFK objectives before outside-world routing.",
        },
        WAILING_CAVERNS = {
            name = "Wailing Caverns",
            dungeon = true,
            zoneAliases = { "Wailing Caverns" },
            note = "Dungeon cluster: full area bonus only while inside Wailing Caverns; outside, entrance proximity is used instead.",
        },
    },

    -- Route classifications:
    -- IMPORTANT = class unlock / major progression
    -- DO        = efficient route step
    -- OPTIONAL  = useful but skippable
    -- SKIP      = poor XP/time
    --
    -- IMPORTANT: Route by quest ID, not quest title. Forever can contain
    -- several quests with the same title.
    --
    -- Optional waypoint format for VERIFIED coordinates only:
    -- waypoint = { mapID = 123, x = 0.50, y = 0.50, label = "NPC / objective" }
    route = {
        {
            questID = 98389,
            class = "ROGUE",
            cluster = "TIRISFAL_DEATHKNELL",
            clusterPriority = 1,
            title = "A Light in the Darkness",
            tag = "DO",
            minLevel = 2,
            maxLevel = 6,
            note = "Forever-specific Deathknell quest. Free webbed Forsaken in Night Web's Hollow; stacks with the spider cave route.",
            objectiveTargets = {
                {
                    objectiveContains = "Webbed Forsaken freed",
                    role = "Free captives",
                    name = "Webbed Forsaken",
                    zone = "Night Web's Hollow, Tirisfal Glades",
                    coords = "around 27, 58",
                    locationType = "CAVE OBJECTIVES",
                    instruction = "Enter Night Web's Hollow around 27, 58 and free webbed Forsaken.",
                    action = "FREE 6 WEBBED FORSAKEN",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.27, y = 0.58, label = "Night Web's Hollow" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Aramis Hammerhand",
                zone = "Deathknell, Tirisfal Glades",
                coords = "31.1, 66.4",
                locationType = "QUEST TURN-IN",
                instruction = "Return to Aramis Hammerhand at 31.1, 66.4.",
                action = "TURN IN A LIGHT IN THE DARKNESS",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.311, y = 0.664, label = "Aramis Hammerhand" },
            },
        },
        {
            questID = 382,
            class = "ROGUE",
            cluster = "TIRISFAL_DEATHKNELL",
            clusterPriority = 1,
            title = "The Red Messenger",
            tag = "DO",
            minLevel = 5,
            maxLevel = 8,
            note = "Immediate Deathknell follow-up to The Scarlet Crusade. Kill Meven Korgal at the same Scarlet camp before leaving the area.",
            waypoint = { mapID = 1420, x = 0.366, y = 0.685, label = "Meven Korgal" },
            objectiveTargets = {
                {
                    objectiveContains = "Scarlet Crusade Documents",
                    role = "Kill / loot",
                    name = "Meven Korgal",
                    zone = "Tirisfal Glades",
                    coords = "36.6, 68.5",
                    locationType = "NAMED MOB — Scarlet camp",
                    instruction = "Kill Meven Korgal at the Scarlet camp around 36.6, 68.5 and loot the documents.",
                    action = "KILL MEVEN KORGAL + LOOT DOCUMENTS",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.366, y = 0.685, label = "Meven Korgal" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Executor Arren",
                zone = "Deathknell, Tirisfal Glades",
                coords = "32.2, 66.0",
                locationType = "QUEST TURN-IN",
                instruction = "Return the Scarlet Crusade Documents to Executor Arren at 32.2, 66.0.",
                action = "TURN IN THE RED MESSENGER",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.322, y = 0.660, label = "Executor Arren" },
            },
            nextPickup = {
                title = "Vital Intelligence",
                npc = "Executor Arren",
                role = "Quest giver",
                zone = "Deathknell, Tirisfal Glades",
                coords = "32.2, 66.0",
                showWhileActive = false,
                waypoint = { mapID = 1420, x = 0.322, y = 0.660, label = "Executor Arren" },
            },
        },
        {
            questID = 8,
            class = "ROGUE",
            deferTurnInForQuestIDs = { 365 },
            cluster = "TIRISFAL_BRILL",
            clusterPriority = 4,
            title = "A Rogue's Deal",
            tag = "DO",
            minLevel = 1,
            maxLevel = 9,
            note = "Classic delivery quest verified present in Forever. Turn it in when entering Brill.",
            turnInTarget = {
                role = "Quest turn-in",
                name = "Innkeeper Renee",
                zone = "Brill, Tirisfal Glades",
                coords = "61.7, 52.0",
                locationType = "QUEST TURN-IN / INN",
                instruction = "Deliver the Nondescript Letter to Innkeeper Renee in Brill at 61.7, 52.0.",
                action = "TURN IN A ROGUE'S DEAL",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.617, y = 0.520, label = "Innkeeper Renee" },
            },
        },
        {
            questID = 365,
            class = "ROGUE",
            cluster = "TIRISFAL_BRILL",
            clusterPriority = 1,
            title = "Fields of Grief",
            tag = "DO",
            minLevel = 4,
            maxLevel = 9,
            note = "Classic quest verified present on Ms. Grab the pumpkins before heading east to Brill so you do not backtrack.",
            waypoint = { mapID = 1420, x = 0.359, y = 0.505, label = "Tirisfal Pumpkin farm" },
            objectiveTargets = {
                {
                    objectiveContains = "Tirisfal Pumpkin",
                    role = "Ground loot",
                    name = "Tirisfal Pumpkin Farm",
                    zone = "Tirisfal Glades",
                    coords = "around 35.9, 50.5",
                    locationType = "FARM — ground objects",
                    instruction = "Loot 10 Tirisfal Pumpkins at the farm north of Deathknell around 35.9, 50.5.",
                    action = "LOOT 10 TIRISFAL PUMPKINS",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.359, y = 0.505, label = "Tirisfal Pumpkin farm" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Apothecary Johaan",
                zone = "Brill, Tirisfal Glades",
                coords = "59.4, 52.4",
                locationType = "QUEST TURN-IN",
                instruction = "Take the pumpkins to Apothecary Johaan in Brill at 59.4, 52.4.",
                action = "TURN IN FIELDS OF GRIEF",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.594, y = 0.524, label = "Apothecary Johaan" },
            },
            nextPickup = {
                title = "Fields of Grief",
                npc = "Apothecary Johaan",
                role = "Quest giver",
                zone = "Brill, Tirisfal Glades",
                coords = "59.4, 52.4",
                showWhileActive = false,
                waypoint = { mapID = 1420, x = 0.594, y = 0.524, label = "Apothecary Johaan" },
            },
        },
        {
            questID = 407,
            class = "ROGUE",
            cluster = "TIRISFAL_BRILL",
            clusterPriority = 2,
            title = "Fields of Grief",
            tag = "DO",
            minLevel = 4,
            maxLevel = 10,
            note = "Classic follow-up in Brill. Very short handoff inside the inn cellar.",
            personTarget = {
                role = "Quest target",
                name = "Captured Scarlet Zealot",
                zone = "Gallow's End Tavern cellar, Brill",
                coords = "62.0, 51.3",
                locationType = "INN CELLAR",
                instruction = "Take the Laced Pumpkin to the Captured Scarlet Zealot in the Gallow's End Tavern cellar at 62.0, 51.3.",
                action = "GIVE THE LACED PUMPKIN TO THE ZEALOT",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.620, y = 0.513, label = "Captured Scarlet Zealot" },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Captured Scarlet Zealot",
                zone = "Gallow's End Tavern cellar, Brill",
                coords = "62.0, 51.3",
                action = "TURN IN FIELDS OF GRIEF",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.620, y = 0.513, label = "Captured Scarlet Zealot" },
            },
        },
        {
            questID = 96656,
            class = "ROGUE",
            deferTurnInForQuestIDs = { 365 },
            cluster = "TIRISFAL_BRILL",
            clusterPriority = 1,
            title = "The Adventurer",
            tag = "DO",
            minLevel = 4,
            maxLevel = 9,
            note = "Forever-exclusive camping intro. Efficient on the Deathknell-to-Brill transition because Eleanor is directly on the route.",
            waypoint = { mapID = 1420, x = 0.572, y = 0.554, label = "Eleanor Shackleton" },
            personTarget = {
                role = "Quest turn-in",
                name = "Eleanor Shackleton",
                zone = "Tirisfal Glades, southwest of Brill",
                coords = "57.2, 55.4",
                locationType = "QUEST TURN-IN / CAMPING",
                instruction = "Speak to Eleanor Shackleton near Brill at 57.2, 55.4.",
                action = "TURN IN THE ADVENTURER",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.572, y = 0.554, label = "Eleanor Shackleton" },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Eleanor Shackleton",
                zone = "Tirisfal Glades, southwest of Brill",
                coords = "57.2, 55.4",
                action = "TURN IN THE ADVENTURER",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.572, y = 0.554, label = "Eleanor Shackleton" },
            },
            nextPickup = {
                title = "The Great Outdoors",
                npc = "Eleanor Shackleton",
                role = "Quest giver",
                zone = "Tirisfal Glades, southwest of Brill",
                coords = "57.2, 55.4",
                showWhileActive = false,
                waypoint = { mapID = 1420, x = 0.572, y = 0.554, label = "Eleanor Shackleton" },
            },
        },
        {
            questID = 96607,
            class = "ROGUE",
            cluster = "TIRISFAL_BRILL",
            clusterPriority = 2,
            title = "The Great Outdoors",
            tag = "DO",
            minLevel = 4,
            maxLevel = 9,
            note = "Forever camping tutorial. Very fast XP because the whole objective is at Eleanor's camp.",
            waypoint = { mapID = 1420, x = 0.572, y = 0.554, label = "Eleanor's Campfire" },
            objectiveTargets = {
                {
                    objectiveContains = "Use the /sit emote near the campfire",
                    role = "Camping tutorial",
                    name = "Eleanor's Campfire",
                    zone = "Tirisfal Glades",
                    coords = "57.2, 55.4",
                    locationType = "CAMPFIRE",
                    instruction = "Stand by Eleanor's campfire and use /sit.",
                    action = "TYPE /SIT BY THE CAMPFIRE",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.572, y = 0.554, label = "Eleanor's Campfire" },
                },
                {
                    objectiveContains = "Boosted Rest",
                    role = "Camping tutorial",
                    name = "Eleanor's Campfire",
                    zone = "Tirisfal Glades",
                    coords = "57.2, 55.4",
                    locationType = "CAMPFIRE",
                    instruction = "Remain seated by the campfire until Boosted Rest is gained.",
                    action = "STAY SEATED UNTIL BOOSTED REST",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.572, y = 0.554, label = "Eleanor's Campfire" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Eleanor Shackleton",
                zone = "Tirisfal Glades",
                coords = "57.2, 55.4",
                action = "TURN IN THE GREAT OUTDOORS",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.572, y = 0.554, label = "Eleanor Shackleton" },
            },
        },
        {
            questID = 86784,
            class = "ROGUE",
            cluster = "TIRISFAL_BRILL",
            clusterPriority = 8,
            title = "Sticks and Bones",
            tag = "OPTIONAL",
            minLevel = 4,
            maxLevel = 10,
            note = "Forever-exclusive side quest. Only do it while already at Eleanor's hill; branch spawns can make it slower than the main route.",
            waypoint = { mapID = 1420, x = 0.565, y = 0.535, label = "Dry Branches" },
            objectiveTargets = {
                {
                    objectiveContains = "Dry Branch",
                    role = "Ground loot",
                    name = "Dry Branches",
                    zone = "Tirisfal Glades",
                    coords = "around 56.5, 53.5",
                    locationType = "GROUND OBJECTS",
                    instruction = "Pick up Dry Branches around Eleanor's hill only if they are easy to find.",
                    action = "OPTIONAL: LOOT 6 DRY BRANCHES",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.565, y = 0.535, label = "Dry Branches" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Eleanor Shackleton",
                zone = "Tirisfal Glades",
                coords = "57.2, 55.4",
                action = "TURN IN STICKS AND BONES",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.572, y = 0.554, label = "Eleanor Shackleton" },
            },
        },
        {
            questID = 383,
            class = "ROGUE",
            deferTurnInForQuestIDs = { 365 },
            cluster = "TIRISFAL_BRILL",
            clusterPriority = 1,
            title = "Vital Intelligence",
            tag = "DO",
            minLevel = 5,
            maxLevel = 9,
            note = "Natural transition quest from Deathknell to Brill. Deliver the documents to Executor Zygand and start the Brill hub.",
            personTarget = {
                role = "Quest turn-in",
                name = "Executor Zygand",
                zone = "Brill, Tirisfal Glades",
                coords = "60.6, 51.8",
                locationType = "QUEST TURN-IN / HUB TRANSITION",
                instruction = "Travel to Brill and deliver the documents to Executor Zygand at 60.6, 51.8.",
                action = "GO TO BRILL + TURN IN VITAL INTELLIGENCE",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.606, y = 0.518, label = "Executor Zygand" },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Executor Zygand",
                zone = "Brill, Tirisfal Glades",
                coords = "60.6, 51.8",
                action = "TURN IN VITAL INTELLIGENCE",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.606, y = 0.518, label = "Executor Zygand" },
            },
        },
        {
            questID = 381,
            class = "ROGUE",
            cluster = "TIRISFAL_DEATHKNELL",
            clusterPriority = 1,
            title = "The Scarlet Crusade",
            tag = "DO",
            minLevel = 2,
            maxLevel = 7,
            note = "Efficient Deathknell follow-up after Night Web's Hollow. Do this local Scarlet camp before leaving for farther objectives.",
            waypoint = { mapID = 1420, x = 0.370, y = 0.680, label = "Scarlet camp" },
            objectiveTargets = {
                {
                    objectiveContains = "Scarlet Armband",
                    role = "Kill / loot",
                    name = "Scarlet Converts / Initiates",
                    zone = "Tirisfal Glades",
                    coords = "around 37, 68",
                    locationType = "SCARLET CAMP — southeast of Deathknell",
                    instruction = "Kill Scarlet Converts and Initiates around 37, 68.",
                    action = "LOOT 12 SCARLET ARMBANDS",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.370, y = 0.680, label = "Scarlet camp" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Executor Arren",
                zone = "Deathknell, Tirisfal Glades",
                coords = "32.2, 66.0",
                locationType = "QUEST TURN-IN",
                instruction = "Return to Executor Arren at 32.2, 66.0.",
                action = "TURN IN THE SCARLET CRUSADE",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.322, y = 0.660, label = "Executor Arren" },
            },
        },
        {
            questID = 6395,
            class = "ROGUE",
            cluster = "TIRISFAL_DEATHKNELL",
            clusterPriority = 3,
            title = "Marla's Last Wish",
            tag = "DO",
            minLevel = 3,
            maxLevel = 7,
            note = "Short Deathknell chain after The Damned. Kill Samuel, loot his remains, bury them at Marla's grave, then return to Novice Elreth.",
            objectiveTargets = {
                {
                    objectiveContains = "Samuel's Remains Buried",
                    requireItemID = 16333,
                    requireItemMissing = true,
                    role = "Kill / loot",
                    name = "Samuel Fipps",
                    zone = "Tirisfal Glades",
                    coords = "36.7, 61.7",
                    locationType = "NAMED MOB",
                    instruction = "Kill Samuel Fipps around 36.7, 61.7 and loot Samuel's Remains.",
                    action = "KILL SAMUEL FIPPS + LOOT REMAINS",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.367, y = 0.617, label = "Samuel Fipps" },
                },
                {
                    objectiveContains = "Samuel's Remains Buried",
                    requireItemID = 16333,
                    requireItemPresent = true,
                    role = "Use quest object",
                    name = "Marla's Grave",
                    zone = "Deathknell graveyard",
                    coords = "31.2, 65.0",
                    locationType = "GRAVE — click the dirt mound",
                    instruction = "Click Marla's grave at 31.2, 65.0 to bury Samuel's Remains.",
                    action = "CLICK MARLA'S GRAVE",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.312, y = 0.650, label = "Marla's Grave" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Novice Elreth",
                zone = "Deathknell, Tirisfal Glades",
                coords = "30.9, 66.1",
                action = "TURN IN MARLA'S LAST WISH",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.309, y = 0.661, label = "Novice Elreth" },
            },
        },
        {
            questID = 380,
            class = "ROGUE",
            cluster = "TIRISFAL_DEATHKNELL",
            clusterPriority = 2,
            title = "Night Web's Hollow",
            tag = "DO",
            minLevel = 2,
            maxLevel = 7,
            note = "Efficient spider cave quest that stacks directly with A Light in the Darkness.",
            objectiveTargets = {
                {
                    objectiveContains = "Night Web Spider",
                    role = "Kill",
                    name = "Night Web's Hollow",
                    zone = "Tirisfal Glades",
                    coords = "around 27, 58",
                    locationType = "SPIDER CAVE",
                    instruction = "Kill the required spiders around and inside Night Web's Hollow.",
                    action = "KILL 10 YOUNG + 8 NIGHT WEB SPIDERS",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.27, y = 0.58, label = "Night Web's Hollow" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Executor Arren",
                zone = "Deathknell, Tirisfal Glades",
                coords = "32.2, 65.6",
                action = "TURN IN NIGHT WEB'S HOLLOW",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.322, y = 0.656, label = "Executor Arren" },
            },
        },
        {
            questID = 376,
            class = "ROGUE",
            cluster = "TIRISFAL_DEATHKNELL",
            clusterPriority = 1,
            title = "The Damned",
            tag = "DO",
            minLevel = 2,
            maxLevel = 5,
            note = "Fast Deathknell collection quest. Stack it with nearby starter kills.",
            turnInTarget = {
                role = "Quest turn-in",
                name = "Novice Elreth",
                zone = "Deathknell, Tirisfal Glades",
                coords = "30.9, 66.1",
                locationType = "QUEST TURN-IN",
                instruction = "Return to Novice Elreth at 30.9, 66.1.",
                action = "TURN IN THE DAMNED",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.309, y = 0.661, label = "Novice Elreth" },
            },
            objectiveTargets = {
                {
                    objectiveContains = "Scavenger Paw",
                    role = "Kill / loot",
                    name = "Scavengers and Duskbats",
                    zone = "Deathknell, Tirisfal Glades",
                    coords = "around 33, 64",
                    locationType = "MOBS — south/east of Deathknell",
                    instruction = "Kill nearby scavengers and duskbats around 33, 64.",
                    action = "LOOT 6 SCAVENGER PAWS + 6 DUSKBAT WINGS",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.33, y = 0.64, label = "Scavengers / Duskbats" },
                },
                {
                    objectiveContains = "Duskbat Wing",
                    role = "Kill / loot",
                    name = "Scavengers and Duskbats",
                    zone = "Deathknell, Tirisfal Glades",
                    coords = "around 33, 64",
                    locationType = "MOBS — south/east of Deathknell",
                    instruction = "Kill nearby scavengers and duskbats around 33, 64.",
                    action = "LOOT 6 SCAVENGER PAWS + 6 DUSKBAT WINGS",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.33, y = 0.64, label = "Scavengers / Duskbats" },
                },
            },
        },
        {
            questID = 3901,
            class = "ROGUE",
            cluster = "TIRISFAL_DEATHKNELL",
            clusterPriority = 2,
            title = "Rattling the Rattlecages",
            tag = "DO",
            minLevel = 1,
            maxLevel = 6,
            note = "Fast Deathknell kill quest that stacks with nearby starter work.",
            turnInTarget = {
                role = "Quest turn-in",
                name = "Shadow Priest Sarvis",
                zone = "Deathknell, Tirisfal Glades",
                coords = "30.8, 66.2",
                locationType = "QUEST TURN-IN",
                instruction = "Return to Shadow Priest Sarvis at 30.8, 66.2.",
                action = "TURN IN RATTLING THE RATTLECAGES",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.308, y = 0.662, label = "Shadow Priest Sarvis" },
            },
            objectiveTargets = {
                {
                    objectiveContains = "Rattlecage Skeleton",
                    role = "Kill",
                    name = "Rattlecage Skeletons",
                    zone = "Deathknell, Tirisfal Glades",
                    coords = "around 33, 62",
                    locationType = "MOBS — graveyard/field",
                    instruction = "Kill Rattlecage Skeletons around 33, 62.",
                    action = "KILL 12 RATTLECAGE SKELETONS",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.33, y = 0.62, label = "Rattlecage Skeletons" },
                },
            },
        },
        {
            questID = 3096,
            class = "ROGUE",
            cluster = "TIRISFAL_DEATHKNELL",
            clusterPriority = 0,
            title = "Encrypted Scroll",
            tag = "IMPORTANT",
            minLevel = 1,
            maxLevel = 4,
            note = "Rogue class introduction. Read the provided scroll and speak to David Trias.",
            turnInTarget = {
                role = "Rogue trainer",
                name = "David Trias",
                zone = "Deathknell, Tirisfal Glades",
                coords = "32.5, 65.7",
                locationType = "CLASS QUEST TURN-IN",
                instruction = "Speak to David Trias in Deathknell at 32.5, 65.7.",
                action = "SPEAK TO DAVID TRIAS",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.325, y = 0.657, label = "David Trias" },
            },
        },
        {
            questID = 3902,
            class = "ROGUE",
            cluster = "TIRISFAL_DEATHKNELL",
            clusterPriority = 3,
            title = "Scavenging Deathknell",
            tag = "DO",
            minLevel = 2,
            maxLevel = 5,
            note = "Very efficient Deathknell box-loot quest; stack with nearby starter kills.",
            objectiveTargets = {
                {
                    objectiveContains = "Scavenged Goods",
                    role = "Loot",
                    name = "Equipment Boxes",
                    zone = "Deathknell, Tirisfal Glades",
                    coords = "around 33, 64",
                    locationType = "GROUND OBJECTS",
                    instruction = "Loot equipment boxes around Deathknell.",
                    action = "LOOT 6 SCAVENGED GOODS",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.33, y = 0.64, label = "Scavenged Goods" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Deathguard Saltain",
                zone = "Deathknell, Tirisfal Glades",
                coords = "31.6, 65.6",
                locationType = "QUEST TURN-IN",
                instruction = "Return to Deathguard Saltain at 31.6, 65.6.",
                action = "TURN IN SCAVENGING DEATHKNELL",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.316, y = 0.656, label = "Deathguard Saltain" },
            },
        },
        {
            questID = 590,
            class = "ROGUE",
            cluster = "TIRISFAL_DEATHKNELL",
            clusterPriority = 4,
            title = "A Rogue's Deal",
            tag = "OPTIONAL",
            minLevel = 1,
            maxLevel = 7,
            note = "Short local Rogue quest. Do it if Calvin is on your path.",
            objectiveTargets = {
                {
                    objectiveContains = "Calvin Montague",
                    role = "Duel",
                    name = "Calvin Montague",
                    zone = "Tirisfal Glades",
                    coords = "38.2, 56.8",
                    locationType = "NPC",
                    instruction = "Defeat Calvin Montague.",
                    action = "DEFEAT CALVIN MONTAGUE",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.382, y = 0.568, label = "Calvin Montague" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Calvin Montague",
                zone = "Tirisfal Glades",
                coords = "38.2, 56.8",
                locationType = "QUEST TURN-IN",
                action = "TURN IN A ROGUE'S DEAL",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.382, y = 0.568, label = "Calvin Montague" },
            },
        },
        {
            questID = 367,
            class = "ROGUE",
            cluster = "TIRISFAL_BRILL",
            clusterPriority = 1,
            title = "A New Plague",
            tag = "DO",
            minLevel = 6,
            maxLevel = 12,
            note = "Strong Brill chain opener; stacks with local beast kills.",
            objectiveTargets = {
                {
                    objectiveContains = "Darkhound Blood",
                    role = "Kill / loot",
                    name = "Darkhounds",
                    zone = "Tirisfal Glades",
                    coords = "around 56, 51",
                    action = "LOOT 5 DARKHOUND BLOOD",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.56, y = 0.51, label = "Darkhounds" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Apothecary Johaan",
                zone = "Brill, Tirisfal Glades",
                coords = "59.4, 52.4",
                action = "TURN IN A NEW PLAGUE",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.594, y = 0.524, label = "Apothecary Johaan" },
            },
        },
        {
            questID = 368,
            class = "ROGUE",
            cluster = "TIRISFAL_BRILL",
            clusterPriority = 2,
            title = "A New Plague",
            tag = "DO",
            minLevel = 6,
            maxLevel = 13,
            note = "Good XP and convenient while working north/west of Brill.",
            objectiveTargets = {
                {
                    objectiveContains = "Vile Fin Scale",
                    role = "Kill / loot",
                    name = "Vile Fin Murlocs",
                    zone = "Tirisfal Glades",
                    coords = "around 50, 35",
                    action = "LOOT 5 VILE FIN SCALES",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.50, y = 0.35, label = "Vile Fin Murlocs" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Apothecary Johaan",
                zone = "Brill, Tirisfal Glades",
                coords = "59.4, 52.4",
                action = "TURN IN A NEW PLAGUE",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.594, y = 0.524, label = "Apothecary Johaan" },
            },
        },
        {
            questID = 369,
            class = "ROGUE",
            cluster = "TIRISFAL_BRILL",
            clusterPriority = 3,
            title = "A New Plague",
            tag = "DO",
            minLevel = 6,
            maxLevel = 14,
            note = "Good continuation of the Brill plague chain.",
            objectiveTargets = {
                {
                    objectiveContains = "Vicious Night Web Spider Venom",
                    role = "Kill / loot",
                    name = "Vicious Night Web Spiders",
                    zone = "Tirisfal Glades",
                    coords = "around 87, 53",
                    action = "LOOT 4 SPIDER VENOM",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.87, y = 0.53, label = "Vicious Night Web Spiders" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Apothecary Johaan",
                zone = "Brill, Tirisfal Glades",
                coords = "59.4, 52.4",
                action = "TURN IN A NEW PLAGUE",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.594, y = 0.524, label = "Apothecary Johaan" },
            },
        },
        {
            questID = 371,
            class = "ROGUE",
            cluster = "TIRISFAL_BRILL",
            clusterPriority = 4,
            title = "At War With The Scarlet Crusade",
            tag = "DO",
            minLevel = 8,
            maxLevel = 15,
            note = "High-XP Scarlet kill chain. Do while sweeping eastern Tirisfal.",
            objectiveTargets = {
                {
                    objectiveContains = "Captain Vachon",
                    role = "Kill",
                    name = "Captain Vachon / Scarlet Friars",
                    zone = "Tirisfal Glades",
                    coords = "around 82, 41",
                    action = "KILL CAPTAIN VACHON + 5 FRIARS",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.82, y = 0.41, label = "Captain Vachon" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Executor Zygand",
                zone = "Brill, Tirisfal Glades",
                coords = "60.6, 51.8",
                action = "TURN IN SCARLET CRUSADE",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.606, y = 0.518, label = "Executor Zygand" },
            },
        },
        {
            questID = 372,
            class = "ROGUE",
            cluster = "TIRISFAL_BRILL",
            clusterPriority = 5,
            title = "At War With The Scarlet Crusade",
            tag = "DO",
            minLevel = 8,
            maxLevel = 16,
            note = "Strong chain finale with a weapon reward choice.",
            objectiveTargets = {
                {
                    objectiveContains = "Captain Melrache",
                    role = "Kill",
                    name = "Captain Melrache / Bodyguards",
                    zone = "Tirisfal Glades",
                    coords = "around 79, 25",
                    action = "KILL MELRACHE + 2 BODYGUARDS",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.79, y = 0.25, label = "Captain Melrache" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Executor Zygand",
                zone = "Brill, Tirisfal Glades",
                coords = "60.6, 51.8",
                action = "TURN IN SCARLET CRUSADE",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.606, y = 0.518, label = "Executor Zygand" },
            },
        },
        {
            questID = 408,
            class = "ROGUE",
            cluster = "TIRISFAL_BRILL",
            clusterPriority = 6,
            title = "The Family Crypt",
            tag = "DO",
            minLevel = 10,
            maxLevel = 16,
            note = "Good Agamand Mills XP; efficient when bundled with nearby Tirisfal work.",
            objectiveTargets = {
                {
                    objectiveContains = "Dargol",
                    role = "Kill",
                    name = "Agamand Family Crypt",
                    zone = "Tirisfal Glades",
                    coords = "around 52, 30",
                    action = "KILL ANCESTORS + CAPTAIN DARGOL",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.52, y = 0.30, label = "Agamand Family Crypt" },
                },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Magistrate Sevren",
                zone = "Brill, Tirisfal Glades",
                coords = "61.3, 50.8",
                action = "TURN IN THE FAMILY CRYPT",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.613, y = 0.508, label = "Magistrate Sevren" },
            },
        },
        {
            questID = 364,
            class = "ROGUE",
            cluster = "TIRISFAL_DEATHKNELL",
            clusterPriority = 1,
            title = "The Mindless Ones",
            tag = "DO",
            minLevel = 1,
            maxLevel = 4,
            note = "Fast Undead starter kill quest. Finish it before leaving Deathknell.",
            personTarget = {
                role = "Quest turn-in",
                name = "Shadow Priest Sarvis",
                zone = "Deathknell, Tirisfal Glades",
                coords = "30.8, 66.2",
                locationType = "QUEST GIVER / TURN-IN",
                locationNote = "Sarvis gives and receives The Mindless Ones.",
                approach = "Return to Shadow Priest Sarvis in Deathknell after killing the zombies.",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.308, y = 0.662, label = "Shadow Priest Sarvis" },
            },
            turnInTarget = {
                role = "Quest turn-in",
                name = "Shadow Priest Sarvis",
                zone = "Deathknell, Tirisfal Glades",
                coords = "30.8, 66.2",
                locationType = "QUEST TURN-IN",
                locationNote = "Return to Sarvis when both zombie objectives are complete.",
                approach = "Go back to Shadow Priest Sarvis in Deathknell.",
                instruction = "Return to Shadow Priest Sarvis at 30.8, 66.2.",
                action = "TURN IN THE MINDLESS ONES",
                useArrow = true,
                waypoint = { mapID = 1420, x = 0.308, y = 0.662, label = "Shadow Priest Sarvis" },
            },
            objectiveTargets = {
                {
                    objectiveContains = "Mindless Zombie",
                    role = "Kill",
                    name = "Mindless / Wretched Zombies",
                    zone = "Deathknell, Tirisfal Glades",
                    coords = "around 33, 63",
                    locationType = "MOBS — outside Deathknell",
                    locationNote = "Both zombie types are clustered just outside the starter village.",
                    approach = "Move out of Deathknell toward the nearby zombie field.",
                    instruction = "Kill Mindless and Wretched Zombies around 33, 63.",
                    action = "KILL 8 MINDLESS + 8 WRETCHED ZOMBIES",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.33, y = 0.63, label = "Mindless Ones" },
                },
                {
                    objectiveContains = "Wretched Zombie",
                    role = "Kill",
                    name = "Mindless / Wretched Zombies",
                    zone = "Deathknell, Tirisfal Glades",
                    coords = "around 33, 63",
                    locationType = "MOBS — outside Deathknell",
                    locationNote = "Both zombie types are clustered just outside the starter village.",
                    approach = "Move out of Deathknell toward the nearby zombie field.",
                    instruction = "Kill Mindless and Wretched Zombies around 33, 63.",
                    action = "KILL 8 MINDLESS + 8 WRETCHED ZOMBIES",
                    useArrow = true,
                    waypoint = { mapID = 1420, x = 0.33, y = 0.63, label = "Mindless Ones" },
                },
            },
            nextPickup = {
                title = "Rattling the Rattlecages",
                npc = "Shadow Priest Sarvis",
                role = "Quest giver",
                zone = "Deathknell, Tirisfal Glades",
                coords = "30.8, 66.2",
                showWhileActive = false,
                waypoint = { mapID = 1420, x = 0.308, y = 0.662, label = "Shadow Priest Sarvis" },
            },
        },
        -- Verified Horde Shaman Call of Water anchor IDs.
        -- These entries intentionally avoid invented coordinates.
        {
            questID = 2986,
            title = "Call of Water",
            tag = "IMPORTANT",
            minLevel = 20,
            maxLevel = 30,
            note = "Shaman Water Totem chain. Keep this quest prioritized until the chain advances.",
        },
        {
            questID = 1534,
            title = "Call of Water",
            tag = "IMPORTANT",
            minLevel = 20,
            maxLevel = 30,
            note = "Continue the Water Totem class chain.",
        },
        {
            questID = 1536,
            title = "Call of Water",
            tag = "IMPORTANT",
            minLevel = 20,
            maxLevel = 30,
            note = "Continue the Water Totem class chain.",
        },
        {
            questID = 220,
            title = "Call of Water",
            tag = "IMPORTANT",
            minLevel = 20,
            maxLevel = 30,
            cluster = "BARRENS_RATCHET",
            clusterPriority = 0,
            note = "Bring the Vial of Purest Water to Islen Waterseer in the Barrens. This continues the Water Totem chain.",
            waypoint = { mapID = 1413, x = 0.658, y = 0.438, label = "Islen Waterseer" },
        },
        {
            questID = 63,
            cluster = "SILVERPINE_WATER",
            clusterPriority = 1,
            title = "Call of Water",
            tag = "IMPORTANT",
            minLevel = 20,
            maxLevel = 30,
            note = "Defeat the Corrupt Manifestation of Water, then use the bracers and remaining pure water at the Brazier of Everfount in Silverpine Forest.",
            waypoint = { mapID = 1421, x = 0.383, y = 0.446, label = "Brazier of Everfount" },
            travelGuide = {
                {
                    zoneAliases = { "The Barrens", "Barrens", "Ratchet" },
                    instruction = "Travel north toward Durotar and Orgrimmar. Your cross-continent route is the Orgrimmar to Undercity zeppelin.",
                },
                {
                    zoneAliases = { "Durotar", "Orgrimmar" },
                    instruction = "Go to the zeppelin tower east of the Orgrimmar entrance and take the zeppelin to Undercity.",
                    waypoint = { mapID = 1411, x = 0.508, y = 0.136, label = "Undercity Zeppelin" },
                },
                {
                    zoneAliases = { "Tirisfal Glades", "Undercity", "Ruins of Lordaeron" },
                    instruction = "From Undercity/Tirisfal, travel southwest into Silverpine Forest. Continue toward the coast west of The Sepulcher.",
                },
                {
                    zoneAliases = { "Alterac Mountains", "Misty Shore" },
                    instruction = "OFF ROUTE: you went past Silverpine into Alterac Mountains near the Misty Shore. Turn back toward Silverpine Forest. The arrow stays hidden until you are back on the verified Silverpine map so it cannot send you the wrong way.",
                },
                {
                    zoneAliases = { "Silverpine Forest", "Silverpine", "The Sepulcher" },
                    instruction = "Follow the terrain route to the hidden pool.",
                    steps = {
                        {
                            instruction = "STEP 1/2: Get to The Sepulcher and move to the west/back side of the inn and catacomb area. Look for the two large trees and rocky ledge. The arrow stays off during this approach so it cannot point you through the cliff.",
                            advanceWhenWithin = {
                                waypoint = { mapID = 1421, x = 0.383, y = 0.446, label = "Hidden pool / Brazier of Everfount" },
                                distance = 0.055,
                            },
                        },
                        {
                            instruction = "STEP 2/2: You are close enough for local guidance. Use the trees/rock ledge to climb over, carefully drop to the hidden pool, use Water Sapta, kill the Corrupt Minor Manifestation of Water, loot the bracers, then click the Brazier and speak to the water elemental.",
                            waypoint = { mapID = 1421, x = 0.383, y = 0.446, label = "Hidden pool / Brazier of Everfount" },
                        },
                    },
                },
                {
                    instruction = "Travel to Silverpine Forest. Use the Orgrimmar to Undercity zeppelin if crossing from Kalimdor, then head west of The Sepulcher.",
                },
            },
        },

        {
            questID = 96,
            flightTarget = "Ratchet",
            cluster = "BARRENS_RATCHET",
            clusterPriority = 0,
            title = "Call of Water",
            tag = "IMPORTANT",
            minLevel = 20,
            maxLevel = 30,
            note = "Final Water Totem hand-in: bring the Shard of Water back to Islen Waterseer in The Barrens. Turn this in before normal leveling quests.",
            waypoint = { mapID = 1413, x = 0.658, y = 0.438, label = "Islen Waterseer - Water Totem turn-in" },
            travelGuide = {
                {
                    zoneAliases = { "Silverpine Forest", "Silverpine", "Tirisfal Glades", "Undercity", "Ruins of Lordaeron" },
                    instruction = "Return to Undercity/Tirisfal and take the zeppelin back to Orgrimmar. Then travel south into The Barrens and return to Islen Waterseer at about 65.8, 43.8.",
                },
                {
                    zoneAliases = { "Durotar", "Orgrimmar" },
                    instruction = "From Orgrimmar, travel south through Durotar into The Barrens, then head to Islen Waterseer at about 65.8, 43.8.",
                },
                {
                    zoneAliases = { "The Barrens", "Barrens", "Ratchet" },
                    instruction = "Go to Islen Waterseer at about 65.8, 43.8 and turn in the Shard of Water. This awards your Water Totem and completes this major class-quest payoff.",
                    waypoint = { mapID = 1413, x = 0.658, y = 0.438, label = "Islen Waterseer - Water Totem turn-in" },
                },
                {
                    instruction = "Return to Islen Waterseer in The Barrens at about 65.8, 43.8 and turn in the Shard of Water.",
                },
            },
        },
        {
            questID = 100,
            cluster = "SILVERPINE_WATER",
            clusterPriority = 2,
            title = "Call of Water",
            tag = "IMPORTANT",
            minLevel = 20,
            maxLevel = 30,
            note = "Speak with the Minor Manifestation of Water at the purified Silverpine shrine. This is part of the Water Totem chain.",
            waypoint = { mapID = 1421, x = 0.383, y = 0.446, label = "Minor Manifestation of Water" },
        },
        {
            questID = 1103,
            flightTarget = "Ratchet",
            cluster = "SILVERPINE_WATER",
            clusterPriority = 3,
            title = "Call of Water",
            tag = "IMPORTANT",
            minLevel = 20,
            maxLevel = 30,
            note = "Recovery step: bring a Water Sapta to Tiev Mordune in Silverpine Forest. The Sapta comes from Islen Waterseer in The Barrens.",
            nextPickup = {
                title = "Water Sapta",
                role = "Quest giver",
                npc = "Islen Waterseer",
                zone = "The Barrens",
                coords = "65.8, 43.8",
                showWhileActive = true,
                useArrow = true,
                note = "Look for a separate quest named Water Sapta from Islen Waterseer. If she does not offer it, the recovery chain may need to be restarted from Tiev Mordune.",
                waypoint = { mapID = 1413, x = 0.658, y = 0.438, label = "Next quest pickup: Water Sapta" },
            },
            travelGuide = {
                {
                    zoneAliases = { "The Barrens", "Barrens", "Ratchet" },
                    instruction = "Get the Water Sapta from Islen Waterseer around 65.8, 43.8, then return to Tiev Mordune in Silverpine Forest.",
                    waypoint = { mapID = 1413, x = 0.658, y = 0.438, label = "Islen Waterseer - Water Sapta" },
                },
                {
                    zoneAliases = { "Silverpine Forest", "Silverpine" },
                    instruction = "You need a Water Sapta for Tiev Mordune. If you do not have one, return to Islen Waterseer in The Barrens around 65.8, 43.8. After obtaining it, come back to Tiev Mordune around 37.3, 44.2 in Silverpine.",
                },
                {
                    instruction = "Obtain a Water Sapta from Islen Waterseer in The Barrens, then bring it to Tiev Mordune in Silverpine Forest around 37.3, 44.2.",
                },
            },
        },

        {
            questID = 1013,
            dungeon = true,
            cluster = "SHADOWFANG_KEEP",
            clusterPriority = 1,
            title = "The Book of Ur",
            tag = "DO",
            minLevel = 18,
            maxLevel = 30,
            note = "Shadowfang Keep dungeon quest. Get The Book of Ur during the run before leaving the instance.",
        },
        {
            questID = 1014,
            dungeon = true,
            cluster = "SHADOWFANG_KEEP",
            clusterPriority = 2,
            title = "Arugal Must Die",
            tag = "DO",
            minLevel = 18,
            maxLevel = 30,
            note = "Shadowfang Keep dungeon quest. Kill Arugal and loot his head before leaving.",
        },
        {
            questID = 1098,
            dungeon = true,
            cluster = "SHADOWFANG_KEEP",
            clusterPriority = 3,
            title = "Deathstalkers in Shadowfang",
            tag = "DO",
            minLevel = 18,
            maxLevel = 30,
            note = "Shadowfang Keep dungeon quest. Keep it with the SFK quest bundle; once complete, finish the remaining in-instance objectives first.",
        },
        {
            questID = 914,
            dungeon = true,
            flightTarget = "Ratchet",
            cluster = "WAILING_CAVERNS",
            clusterPriority = 0,
            title = "Leaders of the Fang",
            tag = "DO",
            minLevel = 18,
            maxLevel = 30,
            note = "Wailing Caverns dungeon quest. Complete all four Fang leaders in one run.",
            waypoint = { mapID = 1413, x = 0.460, y = 0.360, label = "Wailing Caverns cave entrance" },
            personTarget = {
                role = "Dungeon",
                name = "Wailing Caverns",
                zone = "The Barrens",
                coords = "46.0, 36.0",
                locationType = "DUNGEON — enter the cave first",
                locationNote = "The dungeon is inside the Wailing Caverns cave near Lushwater Oasis.",
                approach = "Go to the cave around 46.0, 36.0, enter it, then follow the cave inward to the dungeon portal. Do not climb onto the mountain for this quest.",
                useArrow = true,
                waypoint = { mapID = 1413, x = 0.460, y = 0.360, label = "Wailing Caverns cave entrance" },
            },
            travelGuide = {
                {
                    zoneAliases = { "The Barrens", "Barrens" },
                    instruction = "Go to the Wailing Caverns cave entrance around 46.0, 36.0 near Lushwater Oasis. Enter the cave and follow it inward to the dungeon portal.",
                    waypoint = { mapID = 1413, x = 0.460, y = 0.360, label = "Wailing Caverns cave entrance" },
                },
                {
                    zoneAliases = { "Wailing Caverns" },
                    instruction = "You are inside Wailing Caverns. Stay in the dungeon and complete the remaining Fang leader objectives.",
                },
                {
                    instruction = "If a flight master offers Ratchet, fly there. Then travel west/northwest to the Wailing Caverns cave entrance around 46.0, 36.0.",
                },
            },
        },

        -- Verified from the player's live Forever quest log and current Forever databases.
        -- These are Classic-era quests present in Forever, not confirmed Forever-new quests.
        {
            questID = 6442,
            title = "Naga at the Zoram Strand",
            tag = "DO",
            minLevel = 14,
            maxLevel = 24,
            cluster = "ASHENVALE_ZORAM",
            clusterPriority = 1,
            note = "Fast local kill quest while at Zoram'gar. Kill Wrathtail naga on the nearby coast.",
            objectiveTargets = {
                {
                    objectiveContains = "Wrathtail Head",
                    role = "Kill / loot",
                    name = "Wrathtail Naga",
                    zone = "Zoram Strand, Ashenvale",
                    coords = "around 10, 21",
                    locationType = "MOBS — along the coast",
                    locationNote = "Kill nearby Wrathtail naga and loot their heads.",
                    approach = "Ride north along the coast from Zoram'gar Outpost.",
                    instruction = "Kill Wrathtail naga along Zoram Strand around 10, 21.",
                    action = "LOOT 20 WRATHTAIL HEADS",
                    useArrow = true,
                    waypoint = { mapID = 1440, x = 0.10, y = 0.21, label = "Wrathtail Naga" },
                },
            },
        },
        {
            questID = 6641,
            title = "Vorsha the Lasher",
            tag = "OPTIONAL",
            minLevel = 20,
            maxLevel = 27,
            cluster = "ASHENVALE_ZORAM",
            clusterPriority = 2,
            note = "Elite escort/event. Good if you have help; skip if solo time is tight.",
            objectiveTargets = {
                {
                    objectiveContains = "Vorsha the Lasher",
                    role = "Escort / elite event",
                    name = "Muglash",
                    zone = "Zoram Strand, Ashenvale",
                    coords = "around 12.1, 34.6",
                    locationType = "ELITE EVENT — bring help if needed",
                    locationNote = "Escort Muglash to the brazier, extinguish it, then defend against naga and Vorsha.",
                    approach = "Start with Muglash at Zoram'gar and follow the escort north along the coast.",
                    instruction = "Start Muglash's escort at Zoram'gar; defeat Vorsha when she appears.",
                    action = "ESCORT MUGLASH / KILL VORSHA",
                    useArrow = true,
                    waypoint = { mapID = 1440, x = 0.121, y = 0.346, label = "Muglash — Vorsha event" },
                },
            },
        },
        {
            questID = 216,
            title = "Between a Rock and a Thistlefur",
            tag = "DO",
            minLevel = 21,
            maxLevel = 28,
            cluster = "ASHENVALE_THISTLEFUR",
            clusterPriority = 1,
            note = "Efficient kill quest that stacks with Troll Charm and Logging Rope.",
            objectiveTargets = {
                {
                    objectiveContains = "Thistlefur",
                    role = "Kill",
                    name = "Thistlefur Village",
                    zone = "Ashenvale",
                    coords = "around 35, 39",
                    locationType = "MOBS — furbolg village",
                    locationNote = "Kill Thistlefur Avengers and Shamans here.",
                    approach = "Travel east from Zoram'gar toward Thistlefur Village.",
                    instruction = "Kill Thistlefur mobs around 35, 39.",
                    action = "KILL THISTLEFUR AVENGERS / SHAMANS",
                    useArrow = true,
                    waypoint = { mapID = 1440, x = 0.35, y = 0.39, label = "Thistlefur Village" },
                },
            },
        },
        {
            questID = 6462,
            title = "Troll Charm",
            tag = "DO",
            minLevel = 19,
            maxLevel = 29,
            cluster = "ASHENVALE_THISTLEFUR",
            clusterPriority = 2,
            note = "Stacks with Thistlefur kills; collect charms from chests in Thistlefur Hold.",
            objectiveTargets = {
                {
                    objectiveContains = "Troll Charm",
                    role = "Loot",
                    name = "Troll Charm chests",
                    zone = "Thistlefur Hold, Ashenvale",
                    coords = "around 41, 33",
                    locationType = "CHESTS — inside Thistlefur Hold",
                    locationNote = "Loot the troll charm chests in the cave.",
                    approach = "Enter Thistlefur Hold at the end of the village and look for charm chests.",
                    instruction = "Loot Troll Charms in Thistlefur Hold around 41, 33.",
                    action = "LOOT 8 TROLL CHARMS",
                    useArrow = true,
                    waypoint = { mapID = 1440, x = 0.41, y = 0.33, label = "Thistlefur Hold" },
                },
            },
        },
        {
            questID = 6563,
            title = "The Essence of Aku'Mai",
            tag = "OPTIONAL",
            minLevel = 17,
            maxLevel = 28,
            note = "Blackfathom Deeps dungeon objective. Save it for a BFD run instead of making a standalone trip.",
        },
        {
            questID = 6921,
            title = "Amongst the Ruins",
            tag = "OPTIONAL",
            minLevel = 20,
            maxLevel = 30,
            note = "Blackfathom Deeps dungeon objective. Get the Fathom Core during the same BFD run as other dungeon work.",
        },
        {
            questID = 6543,
            flightTarget = "Splintertree Post",
            cluster = "ASHENVALE_SPLINTERTREE",
            clusterPriority = 1,
            title = "The Warsong Reports",
            tag = "DO",
            minLevel = 17,
            maxLevel = 25,
            note = "Efficient while moving through Ashenvale: it naturally sends you through multiple Horde positions. Complete it alongside nearby Ashenvale quests.",
            turnInFlightTarget = "Crossroads",
            turnInTarget = {
                role = "Quest turn-in",
                name = "Kadrak",
                zone = "Northern Barrens watch tower",
                coords = "48.1, 5.4",
                locationType = "QUEST TURN-IN",
                locationNote = "Kadrak is at the watch tower on the northern edge of The Barrens.",
                approach = "From Crossroads, ride north on the main road to Kadrak's watch tower near the Ashenvale border.",
                instruction = "Return to Kadrak at 48.1, 5.4 in northern The Barrens.",
                action = "TURN IN THE WARSONG REPORTS",
                useArrow = true,
                waypoint = { mapID = 1413, x = 0.481, y = 0.054, label = "Kadrak" },
            },
            objectiveTargets = {
                {
                    objectiveContains = "Warsong Scout Update",
                    role = "Report contact",
                    name = "Warsong Scout",
                    zone = "Ashenvale — near Splintertree Post",
                    coords = "71.1, 68.4",
                    locationType = "OUTDOOR — tower near Splintertree Post",
                    locationNote = "The Scout is at the tower just outside Splintertree Post.",
                    approach = "Go to the tower near Splintertree Post and speak to the Warsong Scout.",
                    instruction = "Head to the tower near Splintertree Post around 71.1, 68.4.",
                    action = "Deliver the Scout report",
                    useArrow = true,
                    waypoint = { mapID = 1440, x = 0.7105, y = 0.6836, label = "Warsong Scout" },
                },
                {
                    objectiveContains = "Warsong Outrider Update",
                    role = "Report contact",
                    name = "Warsong Outrider",
                    zone = "Ashenvale — east road",
                    coords = "patrols around 84, 50",
                    locationType = "MOVING NPC — mounted on a wolf",
                    locationNote = "The Outrider patrols the road toward Warsong Lumber Camp/Azshara and may not have an obvious quest marker.",
                    approach = "Follow the east road around 84, 50 and look for the mounted Warsong Outrider moving along the road.",
                    instruction = "Look along the east road around 84, 50 for the mounted Warsong Outrider; she patrols instead of standing still.",
                    action = "Deliver the Outrider report",
                    useArrow = true,
                    waypoint = { mapID = 1440, x = 0.8400, y = 0.5000, label = "Warsong Outrider patrol road" },
                },
                {
                    objectiveContains = "Warsong Runner Update",
                    role = "Report contact",
                    name = "Warsong Runner",
                    zone = "Zoram'gar Outpost, Ashenvale",
                    coords = "12.2, 34.2",
                    locationType = "OUTDOOR — Horde outpost",
                    locationNote = "The Runner is at Zoram'gar Outpost near the flight master and may not show a normal quest marker.",
                    approach = "Travel west to Zoram'gar Outpost and speak directly to the Warsong Runner near the flight master.",
                    instruction = "Travel to Zoram'gar Outpost on the west coast around 12.2, 34.2.",
                    action = "Deliver the Runner report",
                    useArrow = true,
                    waypoint = { mapID = 1440, x = 0.1221, y = 0.3420, label = "Warsong Runner" },
                },
            },
        },
        {
            questID = 6571,
            title = "Warsong Supplies",
            tag = "OPTIONAL",
            minLevel = 22,
            maxLevel = 30,
            note = "Long multi-zone supply quest. Do local Ashenvale pieces opportunistically; do not let it interrupt a stronger route.",
            objectiveTargets = {
                {
                    objectiveContains = "Warsong Oil",
                    role = "Quest object",
                    name = "Warsong Oil",
                    zone = "Night Run, Ashenvale",
                    coords = "around 66, 55",
                    locationType = "GROUND OBJECT — small green bottle",
                    locationNote = "The oil is found in the satyr camps. Night Run is the preferred lower-risk location.",
                    approach = "Search the Night Run satyr camp for the clickable oil bottle.",
                    instruction = "Search Night Run around 66, 55 for Warsong Oil.",
                    action = "LOOT WARSONG OIL",
                    useArrow = true,
                    waypoint = { mapID = 1440, x = 0.66, y = 0.55, label = "Warsong Oil — Night Run" },
                },
                {
                    objectiveContains = "Logging Rope",
                    role = "Kill / loot",
                    name = "Foulweald Furbolgs",
                    zone = "Greenpaw Village, Ashenvale",
                    coords = "around 55, 61",
                    locationType = "MOB DROP",
                    locationNote = "Logging Rope drops from Ashenvale furbolgs.",
                    approach = "Kill Foulweald furbolgs while nearby until Logging Rope drops.",
                    instruction = "Kill Foulweald furbolgs around 55, 61 for Logging Rope.",
                    action = "LOOT LOGGING ROPE",
                    useArrow = true,
                    waypoint = { mapID = 1440, x = 0.55, y = 0.61, label = "Logging Rope — Foulweald" },
                },
                {
                    objectiveContains = "Warsong Saw Blades",
                    role = "Supply exchange",
                    name = "Pixel",
                    zone = "Splintertree Post, Ashenvale",
                    coords = "around 73, 61",
                    locationType = "NPC — requires Deadly Blunderbuss",
                    locationNote = "Pixel gives the saw blades in exchange for a Deadly Blunderbuss.",
                    approach = "Bring a Deadly Blunderbuss to Pixel near Splintertree Post.",
                    instruction = "Get a Deadly Blunderbuss, then bring it to Pixel near Splintertree Post.",
                    action = "TRADE DEADLY BLUNDERBUSS FOR SAW BLADES",
                    useArrow = true,
                    waypoint = { mapID = 1440, x = 0.73, y = 0.61, label = "Pixel — Saw Blades" },
                },
            },
        },
        {
            questID = 6503,
            flightTarget = "Splintertree Post",
            cluster = "ASHENVALE_SPLINTERTREE",
            clusterPriority = 2,
            title = "Ashenvale Outrunners",
            tag = "DO",
            minLevel = 19,
            maxLevel = 27,
            note = "Good Splintertree-area kill quest. Pair it with other nearby Ashenvale objectives instead of making a separate trip.",
        },
        {
            questID = 6441,
            flightTarget = "Splintertree Post",
            cluster = "ASHENVALE_SPLINTERTREE",
            clusterPriority = 3,
            title = "Satyr Horns",
            tag = "DO",
            minLevel = 21,
            maxLevel = 29,
            note = "Worth doing while questing around Splintertree and the nearby satyr camps. Avoid a long standalone detour just for this quest.",
        },
        {
            questID = 6981,
            flightTarget = "Ratchet",
            cluster = "BARRENS_RATCHET",
            clusterPriority = 1,
            title = "The Glowing Shard",
            tag = "DO",
            minLevel = 15,
            maxLevel = 30,
            note = "Wailing Caverns follow-up. First speak with Sputtervalve beside the Ratchet flight master; he may not show a normal quest marker.",
            personTarget = {
                role = "Quest contact",
                name = "Sputtervalve",
                zone = "Ratchet, The Barrens",
                coords = "63.0, 37.2",
                locationType = "OUTSIDE — Ratchet",
                locationNote = "Sputtervalve stands beside the Ratchet flight master and may not show a normal quest marker.",
                approach = "Stay in Ratchet; go to the flight master area and speak directly to Sputtervalve.",
                useArrow = true,
                waypoint = { mapID = 1413, x = 0.6298, y = 0.3720, label = "Quest contact: Sputtervalve" },
            },
            nextPickup = {
                title = "In Nightmares",
                role = "Quest giver",
                npc = "Falla Sagewind",
                zone = "Wailing Caverns mountain, The Barrens",
                coords = "48.2, 32.8",
                locationType = "OUTSIDE — on top of the Wailing Caverns mountain, NOT inside the dungeon",
                locationNote = "Falla Sagewind is in a small hut on top of the mountain above Wailing Caverns.",
                approach = "Do not enter the Wailing Caverns instance. Approach the mountain from the outside, climb up onto the top, then follow the arrow to Falla around 48.2, 32.8.",
                showWhileActive = false,
                useArrow = true,
                note = "After Sputtervalve advances The Glowing Shard, go to Falla Sagewind on top of the Wailing Caverns mountain for the next quest.",
                waypoint = { mapID = 1413, x = 0.4818, y = 0.3282, label = "Next quest giver: Falla Sagewind" },
            },
        },
        {
            questID = 6548,
            cluster = "STONETALON_GRIMTOTEM",
            clusterPriority = 1,
            title = "Avenge My Village",
            tag = "OPTIONAL",
            minLevel = 12,
            maxLevel = 23,
            note = "Useful if you are already entering Stonetalon, especially because it leads into another short chain step. At level 21, do not travel far out of your way for it.",
        },
        {
            questID = 1062,
            cluster = "STONETALON_GRIMTOTEM",
            clusterPriority = 2,
            title = "Goblin Invaders",
            tag = "OPTIONAL",
            minLevel = 13,
            maxLevel = 23,
            note = "Fine if you are already near the Venture Co. loggers in Stonetalon. Skip a dedicated travel detour at level 21.",
        },
        {
            questID = 1489,
            flightTarget = "Thunder Bluff",
            cluster = "THUNDER_BLUFF",
            clusterPriority = 1,
            title = "Hamuul Runetotem",
            tag = "OPTIONAL",
            minLevel = 12,
            maxLevel = 23,
            note = "Short Wailing Caverns chain handoff. Turn it in when Thunder Bluff fits your travel route; do not make a large standalone trip solely for this step.",
        },
        {
            questID = 3369,
            flightTarget = "Thunder Bluff",
            cluster = "THUNDER_BLUFF",
            clusterPriority = 0,
            title = "In Nightmares",
            tag = "DO",
            minLevel = 18,
            maxLevel = 30,
            note = "Your live Forever quest log confirms this step is complete. Bring the Nightmare Shard to Hamuul Runetotem on Elder Rise in Thunder Bluff.",
            personTarget = {
                role = "Quest turn-in",
                name = "Hamuul Runetotem",
                zone = "Elder Rise, Thunder Bluff",
                locationType = "CITY — Elder Rise, Thunder Bluff",
                locationNote = "Hamuul Runetotem is on Elder Rise in Thunder Bluff. This is a city turn-in, not a dungeon objective.",
                approach = "Travel to Thunder Bluff, enter the city lifts, then go to Elder Rise and find Hamuul Runetotem. Use a flight path to Thunder Bluff if your current flight master offers it.",
            },
            travelGuide = {
                {
                    zoneAliases = { "The Barrens", "Barrens", "Ratchet" },
                    instruction = "FAST ROUTE: Use the nearest flight master and fly to Thunder Bluff if that destination is available. If not, travel southwest through The Barrens into Mulgore, enter Thunder Bluff by lift, then go to Elder Rise and turn In Nightmares in to Hamuul Runetotem.",
                },
                {
                    zoneAliases = { "Mulgore" },
                    instruction = "Head to Thunder Bluff, take a city lift up, then go to Elder Rise and find Hamuul Runetotem.",
                },
                {
                    zoneAliases = { "Thunder Bluff" },
                    instruction = "You are in Thunder Bluff. Go to Elder Rise and find Hamuul Runetotem to turn in In Nightmares.",
                },
                {
                    instruction = "Travel to Thunder Bluff and go to Elder Rise. Turn In Nightmares in to Hamuul Runetotem.",
                },
            },
        },
    },

    fallback = {
        [1] = { tag = "DO", title = "Deathknell", note = "Finish starter quests tightly around Deathknell." },
        [2] = { tag = "DO", title = "Deathknell", note = "Stack The Damned, Rattlecages, Scavenging Deathknell, and Rogue class intro." },
        [3] = { tag = "DO", title = "Deathknell", note = "Finish Deathknell chains; avoid leaving with local quests incomplete." },
        [4] = { tag = "DO", title = "Deathknell → Brill", note = "Finish spider/Scarlet follow-ups, then move toward Brill." },
        [5] = { tag = "DO", title = "Brill", note = "Transition to Brill and start dense Tirisfal chains." },
        [6] = { tag = "DO", title = "Brill / Tirisfal", note = "Stack A New Plague, Scarlet, beast, and local hub quests." },
        [7] = { tag = "DO", title = "Brill / Tirisfal", note = "Stay on dense Brill loops; minimize long single-quest detours." },
        [8] = { tag = "DO", title = "Brill / Tirisfal", note = "Push Scarlet chain and nearby objectives." },
        [9] = { tag = "DO", title = "Brill / Tirisfal", note = "Finish plague/Scarlet loops and Agamand work." },
        [10] = { tag = "DO", title = "Tirisfal → Silverpine", note = "Finish strong Tirisfal chains, then move toward The Sepulcher." },
        [11] = { tag = "DO", title = "Silverpine Forest", note = "Use The Sepulcher as the main hub." },
        [12] = { tag = "DO", title = "Silverpine Forest", note = "Stack village, coast, and Fenris-area quests." },
        [13] = { tag = "DO", title = "Silverpine Forest", note = "Stay on dense Silverpine quest clusters." },
        [14] = { tag = "DO", title = "Silverpine Forest", note = "Do efficient local chains; avoid isolated elite detours unless grouped." },
        [15] = { tag = "DO", title = "Silverpine / RFC option", note = "Quest first; dungeon only when several quests/rewards justify it." },
        [16] = { tag = "DO", title = "Silverpine Forest", note = "Finish major Sepulcher chains and prepare to move south/west." },
        [17] = { tag = "DO", title = "Silverpine → Barrens", note = "Finish strong leftovers, then transition to Barrens." },
        [18] = { tag = "DO", title = "The Barrens", note = "Crossroads/Ratchet quest density becomes the main route." },
        [19] = { tag = "DO", title = "The Barrens", note = "Stack Crossroads, Ratchet, and nearby kill/loot quests." },
        [20] = { tag = "DO", title = "The Barrens", note = "Quest clusters first; Wailing Caverns only with a good quest bundle." },
        [21] = { tag = "DO", title = "Barrens / Stonetalon", note = "Clean Barrens hubs and begin efficient Stonetalon overlaps." },
        [22] = { tag = "DO", title = "Barrens / Stonetalon / Ashenvale", note = "Choose the densest active cluster and stay in it." },
        [23] = { tag = "DO", title = "Stonetalon / Ashenvale", note = "Favor stacked quests over travel-heavy singles." },
        [24] = { tag = "DO", title = "Stonetalon / Ashenvale", note = "Continue dense Horde hubs and worthwhile dungeon bundles." },
        [25] = { tag = "DO", title = "Ashenvale / Stonetalon", note = "Push efficient chains and strong weapon rewards." },
        [26] = { tag = "DO", title = "Ashenvale / Barrens south", note = "Avoid weak detours; stay with clustered objectives." },
        [27] = { tag = "DO", title = "Ashenvale / Thousand Needles prep", note = "Finish strong chains and move only when local density drops." },
        [28] = { tag = "DO", title = "Thousand Needles / Ashenvale", note = "Use the highest-density Horde quest hub available." },
        [29] = { tag = "DO", title = "Finish strongest chains", note = "Prioritize clustered yellow quests and dungeon bundles." },
        [30] = { tag = "IMPORTANT", title = "Level 30 reached", note = "Current Forever cap reached." },
    },
}
